# Generated by Django 4.2 on 2023-05-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
